### ISSUE TITLE
Unhandled Promise Error.

### ISSUE THREAD

**Issue by Asutosh989** [Asutosh989/rss_feeds#13]
> (node:4157) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: Remote server did not respond with a feed

**Comment by iknityanand** [comment]
![image](https://user-images.githubusercontent.com/27820725/31957631-06f86604-b90d-11e7-98dd-1ac8c5bee2ad.png)
can you tell me when does this happen? so I can fix it. pls, check the attached image it seems to be working fine at my end.

**Comment by Asutosh989** [comment]
Its some kind of internet related issues. It is kind of resolved.
