### ISSUE TITLE
https://gitter.im/creating a gitter for quick chat and discussion

### ISSUE THREAD

**Issue by iknityanand** [Asutosh989/rss_feeds#14]
## Possible Solution
it is a suggestion, not an issue but it would be very helpful if we have a gitter thing for chatting and discussing the app. It sometimes takes days to finding and reverting back on comments on GitHub.  On gitter we can stay updated. Gitter is a chat and networking platform that helps to manage, grow and connect communities through messaging, content and discovery. And it is free so please create one.

**Comment by Asutosh989** [comment]
@iknityanand thanks for the suggestion. I shall be opening a slack channel shortly for the discussion purpose.
