### ISSUE TITLE
The feeds are not getting updated on refresh.

### ISSUE THREAD

**Issue by Asutosh989** [Asutosh989/rss_feeds#4]

**Comment by iknityanand** [comment]
working on it

**Comment by Asutosh989** [comment]
Ok

**Comment by iknityanand** [comment]
How can I access mlab db?

**Comment by iknityanand** [comment]
I think the db has limited feeds so it's not getting updated with new info. Access to db will be helpful.

**Comment by Asutosh989** [comment]
ok i get it now. Can you clear the routes. create an account in mlab and update the functions.

**Comment by iknityanand** [comment]
sure thing buddy will work on it.

**Comment by Asutosh989** [comment]
Sure, go on.

**Comment by iknityanand** [comment]
@Asutosh989  I think I might have resolved the issue and submitted a PR. Let me know if it works on your end :)

**Comment by Asutosh989** [comment]
I have seen your PR, it works pretty well. Thanks for your efforts.

**Comment by iknityanand** [comment]
you are welcome you can close this issue. @Asutosh989
