### ISSUE TITLE
Integrate feeds of some popular websites.

### ISSUE THREAD

**Issue by Asutosh989** [Asutosh989/rss_feeds#9]

**Comment by Asutosh989** [comment]
@iknityanand I have created the issue for you. You can start working on it. Do tell if you need anything more.

**Comment by iknityanand** [comment]
yes sure :) @Asutosh989

**Comment by Asutosh989** [comment]
ok

**Comment by iknityanand** [comment]
@Asutosh989 I think I might have resolved the issue and submitted a PR. Let me know if it works on your end :)
